### ISSUE TITLE
Update podinfo example component for MPAS Getting started guide

### ISSUE THREAD

**Issue by souleb** [open-component-model/MPAS#94]
Surface the `SA` from the `podinfo` app into values.yaml, in order to use `imagePullSecrets` generated by a `Target`.

```yaml
serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # List of image pull secrets if pulling from private registries
  imagePullSecrets: []
```
